### ISSUE TITLE
[Feature Request] Open an Specific Workspace as a homepage

### ISSUE THREAD

**Issue by FelipeRearden** [mirnovov/obsidian-homepage#1]
Hello @mirnovov  !!! 

I saw on Discord about this new plug-in and I can wait to use!!!!!! 

I  know it is not released yet but I already have a feature request to share with you :)

As you might know there is a core plug-in called `Workspaces` that lets the user define a set of notes to be display togheter. 
![Screen Shot 2021-07-24 at 08 47 00](https://user-images.githubusercontent.com/85180696/126867580-d04b08a9-2db2-436c-b8fc-04e6697889af.png)
![Screen Shot 2021-07-24 at 08 47 32](https://user-images.githubusercontent.com/85180696/126867581-86217c07-7466-4116-a184-b4cb2b430d52.png)

As an example, this is one of my `Workspaces`
![Screen Shot 2021-07-24 at 08 53 19](https://user-images.githubusercontent.com/85180696/126867599-93d21d1b-9ac6-489f-abdc-a32efafac877.png)

### **My feature request is very simple to explain:** 

Give the option to open an `Workspace` instead of a note. This way I can set a Dashboard Workspace as my homepage in Obsidian.   

I hope you like my suggestion and I hope it is a feasible one :)

Let me know if you need more information.

Thanks and have a great day!

**Comment by mirnovov** [comment]
Added, thanks for the suggestion!

**Comment by FelipeRearden** [comment]
Thank you very much @mirnovov !!!!

As soon as the plug-in is available in the Community Store, I will use and bring some feedback to you. 

Have a great day :)
