### ISSUE TITLE
Homepage + File Color Incompatability

### ISSUE THREAD

**Issue by sudonem** [mirnovov/obsidian-homepage#104]
### Details

With the Homepage plugin enabled and configured to launch a workspace, or daily note on startup (or when no other notes are open) the custom colors applied to files and folders via the [File Color](https://github.com/ecustic/obsidian-file-color) Plugin, all previously configured folder/file colors are disabled.

I suspect it may be related to  another recently reported issue regarding Homepage & Iconize [issue 103](https://github.com/mirnovov/obsidian-homepage/issues/103) given that the issues are both color related.

I am presently using the Iconic plugin (as an alternative to Iconize) which does interact with the icon colors, but I prefer to colorize my files/directories rather than just the icons so i can't speak to compatibility issues there.

### Steps to reproduce

1. Install the File Color Plugin
2. Assign colors to directories or individual files
3. Install the Home Page plugin
4. Configure an action to occur at startup (in this case, opening the Daily Note on startup, or "open when empty").
5. Re-launch obsidian
6. **Observe that colors have been suppressed**
7. Disable homepage plugin
8. Re-launch Obsidian
9. **Observe that colors are now correctly displayed**

![2024-10-06 12 12 19](https://github.com/user-attachments/assets/db60dc82-8867-4c66-9ac2-59eda44df5da)

![2024-10-06 12 13 24](https://github.com/user-attachments/assets/d77f3d87-7604-4784-a191-8d7bd189eb93)

### Debug information

```shell
{"version":4,"homepages":{"Main Homepage":{"value":"Home","kind":"Daily Note","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Editing view (Live Preview)","revertView":false,"openWhenEmpty":true,"refreshDataview":true,"autoCreate":false,"autoScroll":true,"pin":true,"commands":[],"alwaysApply":false,"hideReleaseNotes":false}},"separateMobile":false,"_defaultViewMode":"default","_livePreview":true,"_focusNewTab":"default","_plugins":["table-editor-obsidian","auto-card-link","obsidian-auto-link-title","better-word-count","calendar","colored-tags","obsidian-custom-attachment-location","editing-toolbar","dataview","obsidian-file-color","file-explorer-note-count","multi-properties","nldates-obsidian","omnisearch","obsidian-projects","tag-wrangler","templater-obsidian","text-extractor","obsidian-trash-explorer","frontmatter-modified-date","metaedit","quickadd","obsidian-filename-heading-sync","obsidian-excel-to-markdown-table","obsidian-kindle-plugin","multi-tag","obsidian-tasks-plugin","obsidian-enhancing-export","iconic","obsidian-charts","homepage"],"_internalPlugins":["file-explorer","graph","backlink","canvas","tag-pane","properties","page-preview","daily-notes","note-composer","command-palette","slash-command","editor-status","bookmarks","markdown-importer","outline","file-recovery","sync"],"_obsidianVersion":"1.6.7"}
```

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
This is indeed related to #103. Both are caused by the plugins not accounting for when a workspace is opened, and Homepage uses the same logic as workspaces internally.

There is a workaround in ecustic/obsidian-file-color#26 but given the that plugin no longer seems to be maintained I might add a direct patch on my end.

**Comment by sudonem** [comment]
Well. Nuts.
