### ISSUE TITLE
Sidebar contents disappear on iOS

### ISSUE THREAD

**Issue by tralce** [mirnovov/obsidian-homepage#105]
### Details

Since 1.7.4, setting Homepage to open a file causes the contents of the right sidebar to disappear. Most notably, this hides the sync status indicator.

This has previously been an issue when setting Homepage to open a Workspace, and has previously been proven to be an issue with Workspaces, rather than Homepage. However, in this instance, the same symptoms appear, but only when Homepage is used to open a single file, and does not happen when I manually open the same file with Homepage disabled. 

### Steps to reproduce

- Set Homepage to open a File
- Trigger Homepage
- Look at right sidebar on mobile
- Sync status indicator missing

### Debug information

```shell
The Homepage: Copy debug info command did not actually copy anything to my phone's clipboard and I am thus unable to paste it.
```

### Operating systems

iOS

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
This is partially caused by Obsidian, but I have decided to fix those elements anyway as this is a fairly large issue.
