### ISSUE TITLE
Incompatibility with Auto Folder Collapse

### ISSUE THREAD

**Issue by technotherion** [mirnovov/obsidian-homepage#107]
### Details

Hello. I have created a test vault with only Homepage 4.0.7 and Auto Folder Collapse 1.1.4. 

For some reason, the homepage plugin keeps the file explorer folders from automatically collapsing, keeping the default behavior.
The console shows no errors. 

I've confirmed that this behavior occurs on both Desktop (currently on Linux) and on Mobile (Android). 

### Debug information

```shell
{"version":4,"homepages":{"Main Homepage":{"value":"Home","kind":"File","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Default view","revertView":true,"openWhenEmpty":false,"refreshDataview":false,"autoCreate":false,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":false,"hideReleaseNotes":false}},"separateMobile":false,"_defaultViewMode":"default","_livePreview":"default","_focusNewTab":"default","_plugins":["auto-folder-collapse","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","page-preview","daily-notes","templates","note-composer","command-palette","editor-status","bookmarks","outline","word-count","file-recovery"],"_obsidianVersion":"1.7.4"}
```

### Operating systems

Linux, Android

### Checklist

- [X] I updated to the latest version of the plugin.

Additionally, here's the relevant issue for the Auto Folder Collapse plugin: https://github.com/DarioCasciato/obsidian-auto-folder-collapse/issues/5

**Comment by mirnovov** [comment]
When Homepage loads, the files panel is reloaded as part of changing the vault layout. Internally, it uses the same method that the Workspaces plugin uses, and I can confirm that Auto Folder Collapse doesn't work after a workspace is opened either. 

Although doing this isn't very common it's not exclusive to Homepage so it's best solved on Dario's end, not mine.
