### ISSUE TITLE
Can't select specific file in dropdown

### ISSUE THREAD

**Issue by eacartwright** [mirnovov/obsidian-homepage#110]
### Details

Hi and thank you for the awesome plugin firstly. I'm having an issue with not being able to choose the desired file for my homepage in the options menu. Is there any way to force it if the dropdown can't find the page I'm looking for? Even if I type it correctly it doesn't work unless I successfully click/choose something from the drop down.

In the picture I'm trying to make the root file My.md the homepage, however it keeps looking deeper into the "My" folder structure, if that makes sense. Basically I'm unable to make that root file the homepage at the moment.

![example](https://github.com/user-attachments/assets/f04b432a-ee79-4d6f-a81f-72138b2a1b8d)

### Debug information

```shell
{"version":4,"homepages":{"Main Homepage":{"value":"My","kind":"File","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":true,"openWhenEmpty":true,"refreshDataview":false,"autoCreate":false,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":false,"hideReleaseNotes":true}},"separateMobile":false,"_defaultViewMode":"source","_livePreview":"default","_focusNewTab":"default","_plugins":["todoist-sync-plugin","tray","mrj-text-expand","obsidian-banners","obsidian-view-mode-by-frontmatter","dataview","obsidian-local-rest-api","templater-obsidian","obsidian-sort-and-permute-lines","obsidian-collapse-all-plugin","obsidian-copy-block-link","better-search-views","rendered-block-link-suggestions","buttons","links","link-favicon","obsidian-underline","table-editor-obsidian","obsidian-style-settings","quickadd","obsidian-admonition","obsidian-hider","OA-file-hider","hide-folders","pin-enhancer","shrink-pinned-tabs","obsidian-text-format","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","page-preview","daily-notes","templates","note-composer","command-palette","editor-status","bookmarks","outline","word-count","file-recovery","sync"],"_obsidianVersion":"1.7.7"}
```

### Operating systems

Windows

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by eacartwright** [comment]
I think I have a workaround which is just to append a dot (.) to the desired filename and then select it from the dropdown.

![image](https://github.com/user-attachments/assets/4868d6f4-9dc0-4569-a1da-d4a242af9311)

**Comment by mirnovov** [comment]
If you enter something into the field, by default that will be chosen instead of anything in the dropdown. The dropdown options only take effect if you press <kbd>Enter</kbd>, and you can dismiss the dropdown by clicking outside the field.

This is the same behaviour as other settings fields (i.e. in the Daily Notes plugin). Think of it as more of a list of suggestions instead of mandatory options.
