### ISSUE TITLE
"Command: Open homepage" when homepage is already open 

### ISSUE THREAD

**Issue by Rainbell129** [mirnovov/obsidian-homepage#12]
Dear dev, I have updated the plugin some time ago and encountered a very minor problem. 

I vaguely remember that back a few versions, when the homepage was already opened, running command: open homepage would refresh the site automatically. But after a few updates the command no longer works like this. 

This is a much needed feature for me as I've linked the command to a header button, and would constantly need to refresh my homepage to rerender some dynamic Dataview blocks. Would you consider adding it back if it's not too much trouble?

**Comment by mirnovov** [comment]
I have replicated what older versions of this plugin would have done and it doesn't re-render Dataview. I think your issue may be caused by a change the Dataview maintainers made, not me.

**Comment by Rainbell129** [comment]
> I have replicated what older versions of this plugin would have done and it doesn't re-render Dataview. I think your issue may be caused by a change the Dataview maintainers made, not me.

Thanks for the reply!

Would the command refresh/reopen the page in the older versions? 

I connected the command to a header button using the plug-in customisable page header. I did remember when pressing the button it would reopen the page. Hmmm strange.

![image](https://user-images.githubusercontent.com/58488160/150014926-314957bc-4bf4-4629-9c2d-10f1e4c7fcb8.png)

**Comment by mirnovov** [comment]
> Would the command refresh/reopen the page in the older versions?

Yes, and it still does under certain circumstances. However, it seems like my changes had nothing to do with it, it's just a coincidence. 

I'll see if I can add an option to rerender Dataview though, as other people may find it useful as well.
