### ISSUE TITLE
Cannot Enable Homepage Plugin on Mobile - Phone and iPad

### ISSUE THREAD

**Issue by boksir** [mirnovov/obsidian-homepage#13]
I am unable to enable the Homepage Plugin on Mobile for both Android Phone and iOS iPad. Is this a known issue? Thanks

**Comment by boksir** [comment]
#2 Similar to this issue - but for mobile only

**Comment by mirnovov** [comment]
I am unable to reproduce the issue (iOS on iPhone, I unfortunately don't have either of your devices to test). Have you tried uninstalling and reinstalling the plugin?

**Comment by boksir** [comment]
Yes, that did the trick. Should have tried it before raising the issue.. Thanks.. Closing the issue..
