### ISSUE TITLE
[Feature Request] Be able to use date specifications as homepage name

### ISSUE THREAD

**Issue by pcause** [mirnovov/obsidian-homepage#14]
In Periodic Notes, I can specify a date format for the note location.  For example:

somefolder/YYYY/MM-MMMM/YYYY-MM-DD

with today (march 28, 2022) would have the today note created as:

somefolder/2022/03-March/2022-03-28.md

Allowing this would means my home page when I open Obsidian is the current daily note or a new one is created.

**Comment by mirnovov** [comment]
Closed by #16, thanks to @kzhovn
