### ISSUE TITLE
fr: set different homepage for mobile and desktop

### ISSUE THREAD

**Issue by skyue** [mirnovov/obsidian-homepage#15]
set different homepage for mobile and desktop

**Comment by mirnovov** [comment]
I do plan to get around to this eventually fyi, especially given there seems to be a lot of demand for it. 

In the meantime, if you've a really technically inclined user, you could use some CSS trickery to hide different sections of a page on mobile/desktop.

**Comment by cjolson** [comment]
I would also appreciate this feature. My big need is that I want to set a Workspace to my Homepage, [but Workspaces do not work across different mobile devices](https://forum.obsidian.md/t/workspace-layouts-dont-work-across-different-devices/47453?u=pclaradactyl).  If I could set my Desktop Homepage to a Workspace and the Mobile one to non-workspaces, that would be amazing. 🙏

**Comment by zaen323** [comment]
Just chiming in in 2023 to say that i would appreciate this feature as well!

**Comment by andrewtimberlake** [comment]
Thank you @mirnovov 🎉

**Comment by zaen323** [comment]
Omg thank you!! 🥰🥰
