### ISSUE TITLE
how to use moment-syntax?

### ISSUE THREAD

**Issue by kobalteule** [mirnovov/obsidian-homepage#17]
Hi,
I am trying to set a dynamic homepage with the moment-Syntax. It takes the code I enter into the homepage-field literally.
I tried 

format.moment("YYYY-MM-DD")
format.moment(YYYY-MM-DD) as Obsidian complained about the "
YYYY-MM-DD

A file is always created, but not with the current date but with YYYY-MM-DD

**Comment by mirnovov** [comment]
Hi, the current version of the plugin on the plugin browser doesn't support moment - this will come in a future update.
