### ISSUE TITLE
[bug/feature] Activating homepage with replace open window shouldnt close notes open in sidebar

### ISSUE THREAD

**Issue by danieltomasz** [mirnovov/obsidian-homepage#18]
this is quite critical  for my worklow when I click on homepage or restart Obsidian all  open notes in panes in sidebar are closed
This happens  when I have active   option "replace all open notes". 

I would like to propose option to exclude notes opened in sidebar from replacing

Current I am switch to "replace last note"

**Comment by mirnovov** [comment]
That’s a fairly specific use case so I most likely won’t add that. An option you could consider is the “workspaces” feature of Obsidian, which is supported by this plugin, which allows you to open a whole prespecified layout.

**Comment by danieltomasz** [comment]
In 0.15.3 `open workspace feature` started  closing  the notes opened in sidebar too
