### ISSUE TITLE
This plugin is deleting my home page

### ISSUE THREAD

**Issue by chrisweis** [mirnovov/obsidian-homepage#19]
It deletes the content in my home note during this scenario:

- Enable Daily Notes core plugin's "Open daily note on startup" setting,
- Enable "Use workspaces" in Homepage plugin
- Set the Homepage workspace to a page in the root named "Home"
- Add content into the root home.md file
- Close then open Obsidian (with community plugins enabled)

**Comment by mirnovov** [comment]
The Homepage plugin is designed to be mutually exclusive to "Open daily note on startup" and not work together. It provides similar functionality via the (yet to be released) moment syntax, but even that is not compatible with workspaces as that feature *replaces* all currently open notes (including the daily note opened on startup) with a static, pre-determined set. As it is a core Obsidian feature, adding dynamic functionality to workspaces (such as daily notes) is outside of my plugin's scope.

I will add a warning to the settings pane indicating that "open daily note on startup" is incompatible with my plugin though, thanks for giving me a heads up about it.

**Comment by chrisweis** [comment]
Thanks.  I understood half of that (what is "moment syntax"?) but appreciate the clarification.  I'm uninstalling Homepage for now simply because I fear anything that causes any deletion.  A warning will be super helpful!  It would also be great to know what configuration would prevent any conflicts, if we still want to use your plugin.  For example: Will a conflict between "Open daily note on startup" exist if I avoid using workspaces in Homepage?  Thanks!
