### ISSUE TITLE
Break Since Updating to Obsidian v0.16.2

### ISSUE THREAD

**Issue by micwaab** [mirnovov/obsidian-homepage#20]
Strange bug since updating Obsidian to the insider build. Upon opening Obsidian the homepage does not automatically load. I have to press the homepage button twice before my specified homepage loads. This is persistent and consistent.

**Comment by mirnovov** [comment]
Unfortunately I don't have access to Insider builds, so I cannot diagnose and fix the problem. I'll keep the issue open, and if it persists when 0.16.2 is released publicly, I'll fix it then.

**Comment by mirnovov** [comment]
Fixed by f01606eb45ea4cb8a966369d5dcbcfb80ec58f71
