### ISSUE TITLE
Note only opening in reading view at start 

### ISSUE THREAD

**Issue by Forakt** [mirnovov/obsidian-homepage#22]
Note only opening in reading view at the start of the program, otherwise in edit.

**Comment by mirnovov** [comment]
I can't reproduce this. Would you mind telling me what values these settings are set to?

* Obsidian: 
  * Default view for new tabs
  * Default editing mode
* Homepage:
   * Homepage view
   * Opening method

**Comment by Forakt** [comment]
Obsidian:

- Default view for new tabs (I'm assuming this is editing view)
    - Editing view.
- Default editing mode
    - Live preview
    
    
Homepage:

- Homepage view (I'm assuming this is reading)
    - Reading view
- Opening method
    - Happens when clicking.
    - It opens in reading view when I use hotkey.

Any other plugins you have loaded:

- Admonition

**Comment by mirnovov** [comment]
If you mean clicking on the note in the files sidebar or via a link, that’s intended behaviour. The mode changing only happens when you use the command/icon or when it opens on start. If you click on it as a normal note, the plugin doesn’t know about it.

**Comment by Forakt** [comment]
Oh, that's embarassing. Thought it may have been a bug with 1.0 getting released and all. Didn't mean to waste your time. Thanks for checking in on it, and giving me an answer.

**Comment by mirnovov** [comment]
No problem.
Given that [a plugin](https://github.com/bwydoogh/obsidian-force-view-mode-of-note) that seems to do what you want already exists, I won't implement it for now.
