### ISSUE TITLE
Pressing the Homepage-button closes all open tabs

### ISSUE THREAD

**Issue by KevinvdT** [mirnovov/obsidian-homepage#23]
### Summary

Pressing the Home button closes all open tabs, then opening a new tab with the home page

### Steps to reproduce

Foremost, thanks a lot for developing this plugin. ☺️

#### Current behavior
The new Obisidian update having brought tab support. When pressing the Homepage-button, all open tabs are closed and a new tab with the homepage is opened .

#### Expected behavior (I think)
When pressing the Homepage-button, the homepage opens in the current active tab. All other open tabs are uneffected.

I may be wrong with the expected behavior, but it seems more logical to me. If it is not, then an option to have this behavior would be appreciated.

Removing [src/main.js](https://github.com/mirnovov/obsidian-homepage/blob/5db83a36ffac9003c8c147f3bfd108fa6266d698/src/main.ts#L104) line 404 seems to fix the issue for me, but may produce undesired behavior during startup of Obisidian.

https://github.com/mirnovov/obsidian-homepage/blob/5db83a36ffac9003c8c147f3bfd108fa6266d698/src/main.ts#L104

### Obsidian info

No community plugins besides obisidian-homepage enabled.

### Obsidian version

1.0.0

### Checklist

- [x] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
This is intentional behaviour, but you can change this via the “Opening mode” in settings. Right now there’s not a separate option for startup versus clicking the button, but I can add this.

**Comment by mirnovov** [comment]
I've added the feature in 14185635764a35c2621ffb1bd2dcd1e6a8d9bf02
