### ISSUE TITLE
Data lost ...

### ISSUE THREAD

**Issue by merlinuwe** [mirnovov/obsidian-homepage#24]
### Summary

When I delete all .md files on Android and start Obsidian a homepage file of 0kb is opened and gets synced - to delete the homepage file on other devices.

### Steps to reproduce

1. Delete all .md files on android
2. Delete all .md files in OneDrive in my case
3. Start Obsidian on Android
4. A new file as configured opens with the length of 0KB
5. This file gets synced to the other devices and substitutes the files with the precious contents.

### Obsidian info

Installed homepage plugin
Installed some of the syncing tools (remotely save)

### Obsidian version

2.4.2 (83) API v1.0.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
It is intended behaviour to create a new homepage if it doesn't exist, however I'll add a setting that disables that for use cases like yours.

**Comment by merlinuwe** [comment]
Thank you very much!
