### ISSUE TITLE
Vault deafulting to homepage view mode 

### ISSUE THREAD

**Issue by Ulriksen93** [mirnovov/obsidian-homepage#27]
### Summary

Every time i access my homepage, my vault goes to reading mode

### Steps to reproduce

I set my homepage in reading mode (homepage plugin settings) for formatting issues but the rest of my vault is set to editing view (obsidian settings->editor) (live preview) for the practicality. 

Now every time i acces my homepage, everything goes to reading mode and stops my flow when starting to work on a note.

Is there an easy fix for this? Thanks!

### Obsidian info

Settings > Editor: Default view for new tabs, editing mode and live preview
Settings > Homepage: Homepage default view reading mode

Plugins:
Dataview
tasks
Templatr
banners
file tree alternative plugin
homepage

### Obsidian version

1.1.8

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
There’s no way to automatically restore the previous mode after going to another note from the homepage, but this is as designed, not a big. I’ll consider adding it as a feature though, as this is probably the more convenient behaviour for most people.
