### ISSUE TITLE
New note gets created, existing note is not opened

### ISSUE THREAD

**Issue by jorgb** [mirnovov/obsidian-homepage#3]
Obsidian 0.12.13 - 

When I have a note I want to start up like;

000 MAIN\000 Main MOC

I add that path to the plugin, click on the home icon and it creates an empty note;

000 MAIN\000 Main MOC 1

This happens with most paths I fill in;

100 PLANNING\101 projectplanning

Turns into;

100 PLANNING\101 projectplanning 1

**Comment by mirnovov** [comment]
This appears to because Obsidian doesn't handle Windows-style paths correctly (with `\` instead of `/`). I'll add a workaround.

**Comment by mirnovov** [comment]
Closed in 90b7aea. Thanks for pointing it out!
