### ISSUE TITLE
Option to open HP pinned

### ISSUE THREAD

**Issue by Gewerd-Strauss** [mirnovov/obsidian-homepage#30]
### Summary

We could use an option to automatically pin the homepage once it's opened.

### Details

Hello,

Is it possible to automatically pin the homepage upon startup, so that opening new links won't overwrite it?

As an example, I use the homepage to open my tassks-kanban and my dailynote and pin them automatically, but that is only possible if the HP is pinned itself - otherwhise it will be overwritten.

Thank you.

Sincerely,
~Gw

**Comment by mirnovov** [comment]
This should be solved by the pin option in 2.6, no? Let me know if that doesn’t do what you want.
