### ISSUE TITLE
Can't set obsidian canvas page as homepage

### ISSUE THREAD

**Issue by wizardsd** [mirnovov/obsidian-homepage#31]
### Summary

Can't set obsidian canvas page as homepage

### Steps to reproduce

1. Create new canvas
2. Save the canvas as `My/homepage`
3. Open settings / Homepage
4. Set Homepage to `My/homepage`
5. Click to the Open Homepage button
6. Expect that `My/homepage` canvas will be opened, but receive the message: Homepage "My/homepage" does not exist.

### Obsidian info

Plugins:
![image](https://user-images.githubusercontent.com/6255360/210125619-7b36f50d-0b4e-4235-be33-fde4e9e93fac.png)

Editor:
![image](https://user-images.githubusercontent.com/6255360/210125635-e5e67300-1823-4bd7-9d33-c327e4579f70.png)

Homepage:
![image](https://user-images.githubusercontent.com/6255360/210125656-e1f500ff-9eb8-46c4-9373-495bc37f35fe.png)

### Obsidian version

v1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by wizardsd** [comment]
Unfortunately the issue is partly fixed.
Now I can select `My/homepage.canvas` in the "Homepage" settings, but when I try to open the homepage I get the message: Homepage "My/homepage.canvas" does not exist.

**Comment by mirnovov** [comment]
> Unfortunately the issue is partly fixed.
> Now I can select `My/homepage.canvas` in the "Homepage" settings, but when I try to open the homepage I get the message: Homepage "My/homepage.canvas" does not exist.

Sorry about that @wizardsd. This should be fixed in 73d6e84f20172b487210949f26f9e810bf571622, let me know if your issues persist.

**Comment by wizardsd** [comment]
Yes, now it works as expected! Thank you!
