### ISSUE TITLE
Always open new another homepage tab when jump within homepage when homepage tab is pinned

### ISSUE THREAD

**Issue by hongye007** [mirnovov/obsidian-homepage#32]
### Summary

internal link, pin, jump

### Steps to reproduce

click link like [[#sometitle]] always open new homepage tab when pin setting is true

### Obsidian info

HomePage: 2.7.1

### Obsidian version

1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by hongye007** [comment]
<img width="435" alt="截屏2023-01-07 20 52 43" src="https://user-images.githubusercontent.com/12199008/211151651-c679315c-dabb-4cf8-a524-73e115f3c4ee.png">

**Comment by mirnovov** [comment]
This behaviour occurs when I manually pin a note as well, so it's not related to this plugin.
