### ISSUE TITLE
"Pin on open" feature does not seem to work

### ISSUE THREAD

**Issue by MattiasMartens** [mirnovov/obsidian-homepage#33]
### Summary

When I set the "Pin to homepage when opening" setting, the homepage is not pinned.

### Steps to reproduce

1. Activate the homepage plugin.
2. Set an existing page as the homepage.
3. Close Obsidian completely and reopen.
4. Expectation: Obsidian homepage open and pinned.
5. Reality: Obsidian homepage open but not pinned.

### Obsidian info

Other Installed Plugins:
- Table of Contents
- Cardboard
- Natural Language Dates
- GPT-3 Notes

Default view for new tabs: editing view.
Default editing mode: live preview.
Homepage view: default view.

Operating system: Mac OS X

### Obsidian version

1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Does the tab bar disappear totally, or does the note appear as normal, just not pinned?

**Comment by mirnovov** [comment]
This should fix the issue, but let me know if it persists and I'll reopen it.

**Comment by MattiasMartens** [comment]
thanks @mirnovov, this does indeed fix the issue. i appreciate your work.
