### ISSUE TITLE
Option to force to reopen the homepage only

### ISSUE THREAD

**Issue by FabianoLothor** [mirnovov/obsidian-homepage#35]
### Summary

As a user, I'd like to be able to force the homepage to reload, then some plugins and queries will be refreshed

### Details

Long short story: my homepage uses Obsidian KanBan + Obsidian Tasks and these plugins don't work well together.

---

Kanban loads Tasks only at the very first time that the page opens, if I click in a task, the card will break and to refresh the board I need to do a hard refresh on it, there isn't a "refresh" button, and the plugin doesn't seem to be well maintained.

To quickly refresh the tasks I've two main paths:
1. Using a shortcut, I can press it twice and the board will toggle to markdown and back to the kaban mode.
2. Using the Homepage shortcut I can press a shortcut once to reopen the board.

Those options work fine, but aren't optimal.

The first one requires two shortcuts, and second one requires the option "replace all notes" enabled to do what I want.

The issue with that is that I'd like to be able to replace only the homepage and leave the other notes there, untouched.

Currently this isn't possible with the plugin.

---

That's it, thank you for the amazing job.

---

**[edit]**

The Kanban plugin has a similar behavior if you add DV queries into the cards.

**Comment by mirnovov** [comment]
While I empathise with the difficulty of your workflow, this kinda seems outside the plugin's remit. A "refresh note" feature could actually be useful in a lot of other places not connected to homepages. Therefore, I don't intend to add it at that time, sorry.
