### ISSUE TITLE
No appropriate version found

### ISSUE THREAD

**Issue by maakbaas** [mirnovov/obsidian-homepage#36]
### Summary

When trying to install on IOS I get this error message

### Obsidian info

Trying to install Homepage version 2.7.3 fails with the error message: "No appropriate version found"

### Obsidian version

Obsidian version 1.4.1 (83) API v1.0.3. 

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Thanks for letting me know, should be fixed in 482884065fd1cfdb7d8b70f30a02e880adba87cf
