### ISSUE TITLE
More flexible homepage spec

### ISSUE THREAD

**Issue by pcause** [mirnovov/obsidian-homepage#37]
### Summary

I want to combime a folder path and moment syntax to specify the homepage

### Details

I use the daily notes core plugin.  There you can specify the folder for daily notes and the note name.  It turns out you can use:

YYYY/MM-MMMM/YYYY-MM-DD

as the note name.  This will let it make a directory under the folder for each year, each month and a new page.  So if I have a base folder of /stuff/Inbox/DailyNotes I get a hierarchy that looks like:

stuff/
   - Inbox/
       - DailyNotes/
            - 2022
            - 2023
                - 01-January
                - 02-February
                    - 2023-02-01
                    -  2023-02-02
                    ......
can you use the same kind of logic for specifying the note to open.

**Comment by mirnovov** [comment]
This should work fine with the current version of the plugin. Let me know if you have any issues doing this.
