### ISSUE TITLE
How to stop Homepage from opening at startup?

### ISSUE THREAD

**Issue by tophee** [mirnovov/obsidian-homepage#38]
### Summary

Is there any way of preventing homepage from opening at startup?

### Details

I appreciate the plugin, but when I open Obsidian, I’d like it to show the same note that was open when I last used it. With the homepage plugin enabled, I always get the homepage instead. 

While I see why some people would want it like that, it would be great if this could be disabled. Or perhaps it already is possible and I missed it? Maybe I can manually modify a line of code?

**Comment by mirnovov** [comment]
This isn't a currently possible workflow, but it seems like a pretty obvious use case, so I'll add it.
