### ISSUE TITLE
[Feature Request] Open Homepage in a New Pane

### ISSUE THREAD

**Issue by zcysxy** [mirnovov/obsidian-homepage#4]
Thanks for this plugin! I have a small feature request, that is opening Homepage in a new pane. I often leave many notes open when I leave the app, but Homepage will replace one of them with the home note. FYI I use both Obsidian Tabs and Sliding Panes.

**Comment by mirnovov** [comment]
Should be easy to add, I'll do it soon.

**Comment by mirnovov** [comment]
Closed in fc0e34d, which will be in the next release.
