### ISSUE TITLE
Add MomentJS String Explanation

### ISSUE THREAD

**Issue by segsmachine** [mirnovov/obsidian-homepage#41]
### Summary

Add a simple (but very helpful) explanation

### Details

Many people don't understand that regular strings (like "Daily") can be interpreted as MomentJS syntax

You can add this line under line 91,
 
 ```
You can escape a string of characters using brackets (For example, [Daily]/YYYY-MM-DD) <br>
```

**Comment by mirnovov** [comment]
Good idea, though I'll make the wording a bit terser since the Moment description is already quite verbose.
