### ISSUE TITLE
Homepage view resets to wrong editing mode for opened notes

### ISSUE THREAD

**Issue by cdelog** [mirnovov/obsidian-homepage#42]
### Summary

Switching to the homepage when the "Hompage view" setting is set to "Reading view" resets the preview mode of new notes to "Source Mode".

In short, I don't use the "Source Mode" editing view, I never have, I never want to, sue me. Using the Homepage plugin, I constantly have to reset my edititing view from "Source Mode" to my default, which is "Preview Mode".

### Steps to reproduce

**Setup**
Make sure the "Revert view on close" option is set to ON
Make sure in Options-> Editor that "Default view for new tabs" is in "Editing View"
Make sure in Options -> Editor that "Default editing mode" is "Live Preview"
In Homepage Settings, set "Hompage view" to "Reading view"

**Behavior**
Open Home note -> Should set the view to "Reading View"
Open any note that is not opened (via directory or ctrl+o) -> Should open the note in "Reading View"
Change the new note from "Reading View" to "Editing View" -> The note reverts to "Source Mode"

**Potential Solution**
When you open a note from the Home page, the editing mode should follow the "Default editing mode" configured in Settings->Editor->General

### Obsidian info

Quick Switcher++

### Obsidian version

V1.1.16

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by tpulha** [comment]
This is still happening in my case, exactly as described. App and plugin are updated.

**Comment by mirnovov** [comment]
I can't reproduce this @tpulha. Would you mind sending your Homepage debug info? If you click the button at the bottom of Homepage's settings tab, it should be copied to your clipboard.

**Comment by machado-t** [comment]
{"version":3,"homepages":{"Main Homepage":{"value":"Dashboard","kind":"File","openOnStartup":true,"hasRibbonIcon":true,"openMode":"Keep open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":true,"openWhenEmpty":true,"refreshDataview":false,"autoCreate":true,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":true},"Mobile Homepage":{"value":"Dashboard","kind":"File","openOnStartup":true,"hasRibbonIcon":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Default view","revertView":true,"openWhenEmpty":true,"refreshDataview":false,"autoCreate":true,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":true}},"separateMobile":false,"_defaultViewMode":"default","_livePreview":"default","_focusNewTab":"default","_plugins":["ai-commander","obsidian-auto-link-title","buttons","calendar","callout-manager","cmdr","obsidian-custom-frames","dataview","cm-editor-syntax-highlight-obsidian","obsidian-excel-to-markdown-table","google-calendar","obsidian-hide-sidebars-when-narrow","obsidian-hider","obsidian-ics","obsidian-list-callouts","obsidian-minimal-settings","obsidian-enhancing-export","obsidian42-brat","obsidian-outliner","periodic-notes","recent-files-obsidian","remember-cursor-position","obsidian-rich-links","obsidian-style-settings","supercharged-links-obsidian","templater-obsidian","obsidian-wordy","obsidian-zotero-desktop-connector","bibnotes","dbfolder","obsidian-text-format","markdown-table-editor","workspaces-plus","copilot","text-extractor","obsidian-completr","table-editor-obsidian","obsidian-dictionary-plugin","mousewheel-image-zoom","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","outgoing-link","tag-pane","page-preview","note-composer","command-palette","editor-status","bookmarks","outline","word-count","audio-recorder","workspaces","file-recovery"],"_obsidianVersion":"1.3.7"}

**Comment by mirnovov** [comment]
Thanks, this should be fixed in 08ac9fe which will be included in an upcoming patch.

**Comment by machado-t** [comment]
I can confirm this seems to be fixed.
