### ISSUE TITLE
[FR] Ctrl/Cmd + Click behavior

### ISSUE THREAD

**Issue by juanbretti** [mirnovov/obsidian-homepage#45]
### Summary

Have the same behavior when Ctrl/Cmd + Click as the "Open today's daily note"

### Details

The plugin has the option to "Manual opening method", and we can set it to "Keep open notes", "Replace all open notes", ...
But it could be interesting to make the "Homepage" icon behave the same way as the "Open today's daily note".

When Click on the "Open today's daily note": the page is open in the current tab.
When Ctrl/Cmd + Click on the "Open today's daily note": the page is open in a new tab.

Thank you for your consideration.

**Comment by juanbretti** [comment]
Hello,
I am not able to use the Ctrl/Cmd + Click to open in a new tab.
How can I enable this [FR]?
Thanks!

**Comment by mirnovov** [comment]
Sorry about that, should be fixed in 115d0e3.

**Comment by juanbretti** [comment]
Thank you! Now it works perfectly!

**Comment by juanbretti** [comment]
I understand it's the button 1.
From: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button#value

Something like: https://github.com/mirnovov/obsidian-homepage/commit/115d0e3e44001b757acf6e7f851fb8d92c9a628d#r109211843

**Comment by mirnovov** [comment]
@juanbretti thanks for the suggestion, I've added it in 9ba7ca8.
