### ISSUE TITLE
Using a workspace as a home page doesn't work any more

### ISSUE THREAD

**Issue by Cito** [mirnovov/obsidian-homepage#47]
### Details

After updating to 3.0.1, using a workspace as a homepage doesn't work any more.

### Steps to reproduce

Select an existing workspace as the homepage in the plugin settings.

Press the "Open homepage" shortcut or click on the homepage icon. Nothing happens.

### Debug information

Tested on Windows 11 and Obsidian 1.2.3.

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Does manually triggering the command work? Or pressing the homepage button?

**Comment by mirnovov** [comment]
Should be fixed in 4f49410, sorry about that. Due to the way that I tested this plugin, it didn't show up.

**Comment by Cito** [comment]
Thank you @mirnovov. I can confirm that it's working again in 3.0.2.
