### ISSUE TITLE
"Keep open notes" exception: should replace "New tab"? 

### ISSUE THREAD

**Issue by usernotnull** [mirnovov/obsidian-homepage#49]
### Summary

I have "Keep open notes" for both opening method options.
However, when I open a new tab, then click to open Homepage, I naturally expect the "New tab," which is the blank state where I expect to navigate from, to be replaced by the Homepage instead of opening in another tab.

### Details

"Keep open notes" for me feels like if the note is relevant, the user wants to keep it open and open the homepage on the new tab, however, naturally, I'm treating a new empty tab as "blank," a place where I expect to "override."

Therefore, in the "Keep open notes" logic, there should be an exception and replace the new tab instead of keeping it and opening another tab.

Hopefully, this makes sense. I also thought about any breaking changes and can't think of any.

**Comment by mirnovov** [comment]
Fair enough, I’ll add this.
