### ISSUE TITLE
Get Global Graph View as homepage 

### ISSUE THREAD

**Issue by MatthieuFra** [mirnovov/obsidian-homepage#54]
### Summary

Hi, 

First thanks for your nice plugin ! 

I wanted to ask if it was possible to add a new feature : instead of choosing a file as an homepage, get the graph view of all the vault ? It something that can be very useful to always keep this network in mind and navigate when we launch obsidian.

Thanks, 

MF

**Comment by mirnovov** [comment]
@MatthieuFra this will be incorporated into a future release but in the meantime you can also use the commands feature and it will replace the file Homepage opens

<img width="801" alt="Untitled" src="https://github.com/mirnovov/obsidian-homepage/assets/73574818/cdf507bb-9327-416f-ac20-a4c3a8db666d">
