### ISSUE TITLE
Cannot open notes which use Database folder or Kanban board plugins

### ISSUE THREAD

**Issue by antsam23** [mirnovov/obsidian-homepage#56]
### Details

Hi, when I open notes from homepages, all notes work except for those ones which uses Kanban or DB Folder plugins.
When I click them, page flashes for a moment and then comes back to home.

### Steps to reproduce

Create some DB Folder or Kanban notes, backlink them in home page, open them.

### Debug information

Console doesn't print anything

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
From my testing I can reproduce similar results (though in my case, the tab becomes empty) in the current 3.2.1 build but this should be fixed in 38e2f6b87f81381d1c9e7b5f857043b0e47f149b which will be incorporated in 3.3.

**Comment by antsam23** [comment]
Thank you very much!

**Comment by antsam23** [comment]
Hi @mirnovov , I've just updated to version 3.3 but I continue to see the same error.

**Comment by mirnovov** [comment]
Can you send me your debug info? This is available via a button at the bottom of Homepage's settings. Also, are they just normal links on your homepage, or ones generated by another plugin?

**Comment by antsam23** [comment]
Hi! My links are normal links in an unordered list
These are debug info:
`{"version":3,"homepages":{"Main Homepage":{"value":"Homepage","kind":"File","openOnStartup":true,"hasRibbonIcon":false,"openMode":"Keep open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":true,"openWhenEmpty":true,"refreshDataview":true,"autoCreate":false,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":false}},"separateMobile":false,"_defaultViewMode":"preview","_livePreview":"default","_focusNewTab":"default","_plugins":["recent-files-obsidian","obsidian-kanban","dbfolder","dataview","quickadd","obsidian-spaced-repetition","text-snippets-obsidian","obsidian-banners","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","page-preview","templates","note-composer","command-palette","editor-status","bookmarks","outline","word-count","workspaces","file-recovery"],"_obsidianVersion":"1.3.5"}`

**Comment by mirnovov** [comment]
Thanks, I've been able to reproduce this and will release a fix in the next version.

**Comment by antsam23** [comment]
Hey @mirnovov I've tested it and it works now, thank you very much!
