### ISSUE TITLE
Start with a view

### ISSUE THREAD

**Issue by Weiberle17** [mirnovov/obsidian-homepage#58]
### Summary

I don't know if this is possible because I don't understand how views work in obsidian, so if that's the case I want to apologize in advance.
I would love it if it would be possible to have a view be the homepage. For example the graph view.

### Details

I am using the reminders and calender plugins and both of the views these plugins provide would be awesome to have as a homepage.

**Comment by mirnovov** [comment]
The graph view is built in to the plugin. For other views, most of them should have a command to open the view; you can add it as a command in the settings and it will override the note you have set to open.
