### ISSUE TITLE
every time I reopen Obsidian, the Homepage plugin will open identical homepage pages

### ISSUE THREAD

**Issue by FeiLZX3Km** [mirnovov/obsidian-homepage#59]
### Details

I don't know why, but every time I reopen Obsidian, the Homepage plugin before version 3.3.2 will open 10 or more identical homepage pages. The problem was partially resolved after updating to version 3.3.2 of the plugin, but today I encountered the problem again. When I reopen Obsidian, this plugin will open two identical Homepage pages at the same time, but I still cannot find the problem or solve it.

### Steps to reproduce

Open Obsidian

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
I can't reproduce this. Can you send the debug info, which can be obtained by clicking the button at the bottom of Homepage settings?

**Comment by FeiLZX3Km** [comment]
> I can't reproduce this. Can you send the debug info, which can be obtained by clicking the button at the bottom of Homepage settings?

{"version":3,"homepages":{"Main Homepage":{"value":"998.其他/首页","kind":"File","openOnStartup":true,"hasRibbonIcon":true,"openMode":"Keep open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":false,"openWhenEmpty":false,"refreshDataview":true,"autoCreate":false,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":true}},"separateMobile":false,"_defaultViewMode":"preview","_livePreview":true,"_focusNewTab":true,"_plugins":["remotely-save","obsidian-advanced-uri","oz-clear-unused-images","obsidian-frontmatter-tag-suggest","obsidian-memos","settings-search","consistent-attachments-and-links","obsidian-image-auto-upload-plugin","number-headings-obsidian","obsidian-hypothesis-plugin","recent-files-obsidian","dataview","periodic-notes","editing-toolbar","obsidian-linter","obsidian-scroll-to-top-plugin","table-editor-obsidian","obsidian-footnotes","obsidian-style-settings","open-in-new-tab","obsidian-excalidraw-plugin","floating-toc","obsidian-image-toolkit","obsidian-custom-frames","obsidian-quiet-outline","easy-typing-obsidian","obsidian-tree-leaf","obsidian-dice-roller","homepage","multi-column-markdown"],"_internalPlugins":["file-explorer","global-search","backlink","canvas","outgoing-link","tag-pane","page-preview","daily-notes","templates","note-composer","command-palette","bookmarks","outline","slides","file-recovery"],"_obsidianVersion":"1.2.7"}

**Comment by mirnovov** [comment]
Seems to be a conflict with `open-in-new-tab`. Due to the nature of that plugin, it's not easy to fix this on my side, but I've made a patch to update that plugin's behaviour [here](https://github.com/patleeman/obsidian-open-in-new-tab/pull/9).
