### ISSUE TITLE
Home.md file truncated several times recently

### ISSUE THREAD

**Issue by kaesler** [mirnovov/obsidian-homepage#60]
### Details

I use the plugin on a Mac, iPhone and iPad, all synced by storing the vault in iCloud. Twice in the past week, I found the Home.md file truncated to zero bytes.

No other files in the vault have been truncated ,as far as I can tell.

### Steps to reproduce

No idea how to reproduce reliably I'm afraid. Maybe it is due to problems with iCloud syncing. More of an FYI report.

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
I’d try turning auto-create off and seeing if the problem persists. What is most likely happening is that Homepage is opening it while being in the process of syncing.

**Comment by kaesler** [comment]
Good idea. That sounds promising. Will try shortly. Thanks for this nice plugin.

**Comment by mirnovov** [comment]
I still cannot replicate this, I'm afraid :/

**Comment by kaesler** [comment]
No worries. Feel free to close as unreproducible.  Turning off both “Auto create” and “Open on startup” seems to avoid the problem.
