### ISSUE TITLE
When opening a pinned note with codeblocks, Homepage gets deleted whenever Obsidian is restarted

### ISSUE THREAD

**Issue by Kenljs** [mirnovov/obsidian-homepage#62]
### Details

My Homepage gets deleted whenever I close and reopen obisidan. I am adding buttons (using the buttons plugin) to perform simple actions like open recently edited files. 

This happens 90% of the time if I create a homepage and close then open the app. I also have Homepage installed on my phone.

### Debug information

```shell
{"version":3,"homepages":{"Main Homepage":{"value":"Home","kind":"File","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":true,"openWhenEmpty":true,"refreshDataview":false,"autoCreate":true,"autoScroll":false,"pin":true,"commands":[],"alwaysApply":false}},"separateMobile":false,"_defaultViewMode":"default","_livePreview":true,"_focusNewTab":"default","_plugins":["readwise-official","obsidian-mind-map","note-refactor-obsidian","recent-files-obsidian","better-word-count","tag-wrangler","obsidian-underline","obsidian-style-settings","cm-typewriter-scroll-obsidian","obsidian-textgenerator-plugin","calendar","obsidian-toggle-list","remember-cursor-position","obsidian-smarter-md-hotkeys","obsidian-hider","cmdr","obsidian-excalidraw-plugin","obsidian-pandoc","obsidian-enhancing-export","hotkeysplus-obsidian","obsidian-hotkeys-for-specific-files","obsidian-advanced-slides","omnisearch","insert-unsplash-image","text-extractor","copy-as-html","obsidian-zotero-desktop-connector","obsidian-footnotes","buttons","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","page-preview","daily-notes","templates","note-composer","command-palette","slash-command","bookmarks","outline","word-count","slides","workspaces","file-recovery"],"_obsidianVersion":"1.3.7"}
```

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Do you use iCloud or any other sync solution to sync your vault?

**Comment by ckelley4212** [comment]
I would like to report the same behavior.

**Comment by mirnovov** [comment]
I can now reproduce this by using the Buttons plugin and placing a button on the homepage. This is very odd, as that plugin shouldn't affect note creation, but I should hopefully be able to devise a fix.

**Comment by mirnovov** [comment]
> I would like to report the same behavior.

@ckelley4212 are you using buttons as well?

**Comment by ckelley4212** [comment]
Yes! That’s actually what I added just before i noticed it.

**Comment by Kenljs** [comment]
Thank you! I am eager to use this now. You probably dont need this information now, but I was using buttons as well. I also was using onedrive and the app OneSync to sync files.
Excited to use Homepage now. Thanks again.
