### ISSUE TITLE
Homepage replaces a note that's opened using a callback url

### ISSUE THREAD

**Issue by kimaldis** [mirnovov/obsidian-homepage#65]
### Summary

If a note is opened by some external app using a callback url, Homepage overrides this, showing the home page. Is there a way to prevent this or if not, could there be?

thanks.

**Comment by mirnovov** [comment]
this should be doable, thanks for pointing this out!

**Comment by kimaldis** [comment]
My pleasure :-)

**Comment by mirnovov** [comment]
Fixed in 07e2f15.
