### ISSUE TITLE
How about getting to work on Obsidian Mobile?

### ISSUE THREAD

**Issue by guihasparyk** [mirnovov/obsidian-homepage#68]
### Summary

I've recently used the app on my PC and it's amazing. Can you make it available also for Obsidian Mobile?

### Details

I need it to work on my mobile because some links inside the properties of pages are persistent and end up opening in the same tab, even though I have my plugin "Open In New Tab" activated.

In that way I can have a work fluid of opening links and making notes for my research.

**Comment by mirnovov** [comment]
This seems like an issue with that plugin, not this one.
