### ISSUE TITLE
(Windows 10) Obsidian Fails to Launch anytime an Obsidian Update comes out

### ISSUE THREAD

**Issue by who-took-hu4d** [mirnovov/obsidian-homepage#71]
### Details

You know how when the app updates, on launch it opens that 'Release Notes' note with a little changelog? Any time that this happens obsidian fails to launch unless Homepage is manually disabled in the community-plugins.json file in my .obsidian folder.

This issue has not appeared for me on either my iPhone or my Macbook.

The exact error Obsidian gives is "Type Error cannot be read from null (reading 'parent')"

### Steps to reproduce

Wait for obsidian to update, I guess? Can't exactly force that to happen.

I'm not even super 100% sure that this is the issue, but it's happened twice now and I *think* that this is it. Makes a little bit of sense though since Homepage automatically opens a page and the Release Notes is also automatically opened

### Debug information

```shell
{"version":3,"homepages":{"Main Homepage":{"value":"Dashboard","kind":"File","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":true,"openWhenEmpty":false,"refreshDataview":false,"autoCreate":true,"autoScroll":false,"pin":true,"commands":[],"alwaysApply":false}},"separateMobile":false,"_defaultViewMode":"preview","_livePreview":false,"_focusNewTab":"default","_plugins":["table-editor-obsidian","better-fn","buttons","callout-manager","obsidian-contextual-typography","obsidian-dynamic-toc","obsidian-hotkeys-for-templates","ninja-cursor","zoottelkeeper-obsidian-plugin","text-extractor","obsidian-style-settings","obsidian-sortable","obsidian-query-control","obsidian-paste-as-html","obsidian-pandoc","create-note-in-folder","obsidian-tidy-footnotes","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","page-preview","daily-notes","templates","note-composer","command-palette","editor-status","bookmarks","zk-prefixer","outline","word-count","file-recovery"],"_obsidianVersion":"1.4.16"}
```

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Unfortunately I can't reproduce this when testing on Windows 10 (via installing an [older version](https://github.com/obsidianmd/obsidian-releases/releases) of Obsidian and then upgrading it).

However I've added an option to disable the release notes, as this is a feature that I've been wanting to implement for a while and you may find it a suitable workaround.
