### ISSUE TITLE
Homepage-specific viewing mode no longer works

### ISSUE THREAD

**Issue by krlhBlupine** [mirnovov/obsidian-homepage#73]
### Details

Basically what it says here. No matter what settings used for the homepage viewing mode it always opens in the obsidian default. I'm on version 3.6.0 of Homepage, and 1.4.16 of Obsidian. Bug occurs on both my Archlinux pacman install and on the Ubuntu snap.

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Can’t reproduce this. What other plugins do you have? This can be obtained via the ‘show debug info’ obsidian command.

**Comment by krlhBlupine** [comment]
Output from the command below.

```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000 6.5.9-arch2-1
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: AnuPpuccin v1.4.4
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 33
	Plugins enabled: 13
		1: Longform v2.0.4
		2: Status Bar Pomodoro Timer v0.1.14
		3: Remember cursor position v1.0.8
		4: Style Settings v1.0.7
		5: Templater v1.16.4
		6: Unique attachments v1.0.3
		7: Homepage v3.6.0
		8: Dataview v0.5.64
		9: Completr v3.2.0
		10: Colored Text v0.6.0
		11: Callout Manager v1.0.1
		12: Calibre v1.0.8
		13: Linter v1.20.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by mirnovov** [comment]
Thanks for sending me this. Unfortunately, I still can't get the behaviour to happen. If you disable your other plugins does it still persist?

**Comment by krlhBlupine** [comment]
It does. I wouldn't think it's the specific nature of the homepage itself (it's just a couple of dataview tables), but I can send that as well if you'd like. Additionally, here's the output from the Homepage debug button: 

`{"version":3,"homepages":{"Main Homepage":{"value":"home","kind":"File","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Replace last note","view":"Reading view","revertView":true,"openWhenEmpty":false,"refreshDataview":true,"autoCreate":true,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":true,"hideReleaseNotes":true}},"separateMobile":false,"_defaultViewMode":"default","_livePreview":true,"_focusNewTab":true,"_plugins":["homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","page-preview","daily-notes","templates","note-composer","command-palette","editor-status","bookmarks","zk-prefixer","outline","word-count","audio-recorder","file-recovery"],"_obsidianVersion":"1.4.16"}`

**Comment by krlhBlupine** [comment]
Unfortunately I'm not exactly sure how to get at the obsidian logs themselves, or the plugins logs- any pointers there?

**Comment by krlhBlupine** [comment]
No logs apparently, but I found this in the developer console:

`Homepage: home (method: Replace all open notes, view: Reading view, kind: File)`

Notably this is after the homepage still opened in editing mode.

**Comment by mirnovov** [comment]
That last message is normal. Thanks for sending me all the info, I’ll see if I can reproduce it now.

**Comment by mirnovov** [comment]
Is your actual homepage file called 'Home' with an uppercase 'H'? I can reproduce this when the setting is set to 'home' with a lowercase h but the file has an uppercase one.

Changing 'home' to 'Home' should solve your problem. Basically, Homepage treats these as the same for opening files but the view reversion functionality treats them as different. I'm aware that Linux is case sensitive but Homepage uses Obsidian's link resolution logic which AFAIK is the same on all platforms.

**Comment by krlhBlupine** [comment]
That was the issue, changing the file to 'Home' fixed it.
