### ISSUE TITLE
How to manage the white space below the banner

### ISSUE THREAD

**Issue by antsam23** [mirnovov/obsidian-homepage#74]
Hi! I have a banner like this:

```
---
cssclass: dashboard
banner: "![[Home Banner.png]]"
banner_y: 0.4575
---
```

But below my banner there is a great empty space before the first line which is an header 1.
Is there a way to manage it?

**Comment by mirnovov** [comment]
This plugin doesn’t control the banners. Are you sure you didn’t mean to open this issue in the noatpad/obsidian-banners repo?

**Comment by antsam23** [comment]
Oh! I didn't know that, thank you very much for your help ;)
