### ISSUE TITLE
Separate mobile homepage

### ISSUE THREAD

**Issue by nestor50** [mirnovov/obsidian-homepage#75]
Hello, 
since I've started syncing with Obsidian Sync I'm using obsidian also on mobile version and I saw there's an option to "Separate mobile homepage" but I don't understand how it work. I think I got the idea i.e. having two different homepages for desktop and mobile but I don't get how to set the two files, could you help me?
loops..and thanks for the great plugin!

**Comment by mirnovov** [comment]
You've not the first person to be confused by this, I should probably make it more intuitive at some point.

Basically, if the option is checked, all the changes you make to Homepage's settings on mobile will be stored separately from the ones you make on desktop (once the setting to "Use separate mobile homepage" is synced to both devices of course).

So you would set your mobile page on your phone and your desktop one on the computer. It is designed this way so you can change any setting, not just the page name - let's say you want to use a workspace on desktop but a note or canvas on mobile.

**Comment by nestor50** [comment]
Thanks a lot Mirnovov, made a try and it works perfectly! Inviato da iPadIl giorno 14 dic 2023, alle ore 05:50, mirnovov ***@***.***> ha scritto:﻿
You've not the first person to be confused by this, I should probably make it more intuitive at some point.
Basically, if the option is checked, all the changes you make to Homepage's settings on mobile will be stored separately from the ones you make on desktop (once the setting to "Use separate mobile homepage" is synced to both devices of course).
So you would set your mobile page on your phone and your desktop one on the computer. It is designed this way so you can change any setting, not just the page name - let's say you want to use a workspace on desktop but a note or canvas on mobile.
