### ISSUE TITLE
"Open another vault" window as homepage

### ISSUE THREAD

**Issue by flip-rossi** [mirnovov/obsidian-homepage#76]
### Summary

Instead of opening a specific note or vault when launching Obsidian, open just the "Open another vault" window.

### Details

I use several vaults for different kinds of notes and, when I first launch Obsidian each time, I might not want to use the same vault as the last time.

**Comment by mirnovov** [comment]
You should be able to use the “Open another vault” command. Keep in mind that you’ll probably have to set this up for all of your vaults unless you always close Obsidian on a certain vault.

**Comment by flip-rossi** [comment]
Thanks for the suggestion, I hadn't thought of that

This works but the last vault will still open unnecessarily (and it still has to take its time to fully load) and the new vault will open in a new window instead of substituting the old one.

But yeah, I just now realized that what I suggested might not be fully possible as plugins can only be loaded per vault.

**Comment by mirnovov** [comment]
yeah unless I'm mistaken that's the case, I'm afraid. I'll close this issue as I can't really implement something better than that.
