### ISSUE TITLE
Add setting to not use home config when opening from deep link

### ISSUE THREAD

**Issue by racquetmaster** [mirnovov/obsidian-homepage#81]
### Summary

Add setting to not use home config when opening from deep link

### Details

Using a deep link to open a specific note from another application isn't compatible with this plugin. It opens the home page instead of the destination link.

**Comment by mirnovov** [comment]
@racquetmaster what platform are you using? Deep links are handled by different mechanisms on different platforms. From my testing, it currently works fine on Mac but is broken on iOS.

**Comment by racquetmaster** [comment]
It happens in android. It does seem to open the deep linked page but then the home note opens afterwards.

**Comment by mirnovov** [comment]
Unfortunately I don’t have an Android device to test on.
