### ISSUE TITLE
Interaction with Iconize and Plugin Startup Ordering

### ISSUE THREAD

**Issue by namtrah** [mirnovov/obsidian-homepage#86]
### Details

It seems when I try to use icons from the Iconize plugin that they are not active when Homepage opens its marked Note. Only by closing the note and reopening it (whether automatically or manually) will the icons be seen.

I believe this has to do with the ordering of the startup of the plugins. I do not know how to fix this from an Obsidian side (have asked in the Discord), but thought I would also like to make this apparent to you in case you can do some magic to reload after all plugins have been loaded.

### Steps to reproduce

1. Install Homepage and Iconize plugins
2. Create a Note and mark it as the "Homepage"
3. In this note use a few Icons from the [Iconize plugin](https://github.com/FlorianWoelki/obsidian-iconize)
    1. Examples
        - :FasChartColumn: 
        - :FasBrain: 
        - :FasMemory: 
        - :FasVideo:
        - :FasRecycle: 
4. Reload Obsidian to see that these icons are still text strings and not replaced by Iconize.

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
From my testing, Iconize fails to insert icons with files loaded on startup, even without Homepage. When I open a file with icons, close Obsidian, and then reopen Obsidian, the icons are not successfully rendered on startup.

So unless you can't reproduce this behaviour, this is an issue with Iconize failing to handle files loaded on startup, not Homepage.
