### ISSUE TITLE
Homepage Plugin removes pinned nodes from sidebar at each restart

### ISSUE THREAD

**Issue by stelo-lg** [mirnovov/obsidian-homepage#89]
### Details

I have added some pinned notes in my left and right sidebar. But every time I restarted Obsidian, they were gone. While disabling all the community plugins one after another, I figured, that the Homepage plugin is causing the issue. 

### Steps to reproduce

1. Activate the Homepage plugin.
2. Add a note to the sidebar and pin it. 
3. Restart Obsidian. 

### Debug information

```shell
{"version":3,"homepages":{"Main Homepage":{"value":"Home","kind":"File","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":true,"openWhenEmpty":true,"refreshDataview":false,"autoCreate":true,"autoScroll":false,"pin":true,"commands":[],"alwaysApply":true,"hideReleaseNotes":false}},"separateMobile":false,"_defaultViewMode":"preview","_livePreview":true,"_focusNewTab":"default","_plugins":["obsidian-icon-folder","obsidian-banners","calendar","dataview","folder-note-plugin","waypoint","theme-picker","tag-summary-plugin","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","properties","page-preview","templates","note-composer","command-palette","slash-command","editor-status","bookmarks","random-note","outline","workspaces","file-recovery","sync"],"_obsidianVersion":"1.6.5"}
```

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Homepage currently doesn’t have any way of distinguishing notes in the sidebar from notes in other locations, so this is expected behaviour. It might be worth adding some logic to omit notes from the sidebar from being closed though, as you’ve not the first person to raise this, though I’m not sure how feasible this is.
