### ISSUE TITLE
impossible to download the plugin via BRAT and also via community channel.

### ISSUE THREAD

**Issue by calimbrasti94** [mirnovov/obsidian-homepage#90]
### Details

![image](https://github.com/mirnovov/obsidian-homepage/assets/79490114/151d9f24-6633-4ef4-8d9d-ad6d602675b2)

### Steps to reproduce

I was updating the plugin but it was not possible. it gave me 404 error.

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by marconoris** [comment]
I can't update or download from community channel: "an error occurred"...
