### ISSUE TITLE
Icon not showing correctly

### ISSUE THREAD

**Issue by Aurnytoraink** [mirnovov/obsidian-homepage#94]
### Details

The bug doesn't seem to be related to the selected theme, since it's still present with the default theme.
I've got the same problem on my Android phone too.

I don't have any further explanation, but here is a screenshot that illustrate the bug.

![Icon banner selector](https://github.com/user-attachments/assets/b0bd1477-0408-43a3-8b0a-07ad03475163)
 
![Capture d’écran du 2024-07-23 09-23-08](https://github.com/user-attachments/assets/b65833b2-9270-40da-91ed-95977814d293)

### Steps to reproduce

1. Add an banner_icon

### Debug information

```shell
{"version":4,"homepages":{"Main Homepage":{"value":"99 - Ressources/00 - Accueil","kind":"File","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":true,"openWhenEmpty":true,"refreshDataview":true,"autoCreate":false,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":false,"hideReleaseNotes":false}},"separateMobile":false,"_defaultViewMode":"default","_livePreview":"default","_focusNewTab":"default","_plugins":["remotely-save","templater-obsidian","calendar","obsidian-kanban","obsidian-icon-folder","obsidian-emoji-toolbar","dataview","heatmap-calendar","obsidian-minimal-settings","obsidian-style-settings","obsidian-image-gallery","homepage","obsidian-banners","obsidian-excalidraw-plugin"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","page-preview","daily-notes","templates","note-composer","command-palette","editor-status","bookmarks","outline","word-count","audio-recorder","file-recovery"],"_obsidianVersion":"1.6.7"}
```

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Does this occur when Homepage is disabled? 

Since from my testing, this happens regardless of whether Homepage is active, and instead seems to be related to the emoji image hosting having issues. If you disable "Use Twemoji" in Banner's settings, that seems to fix it for me.
