### ISSUE TITLE
I've encountered a critical bug and need assistance.

### ISSUE THREAD

**Issue by mango618** [mirnovov/obsidian-homepage#97]
### Details

On macOS, the latest version of the plugin conflicts with Obsidian version 1.6.7. The conflict causes the screen to go black after opening Obsidian, making it impossible to perform any actions. This bug also syncs to the mobile app, preventing it from opening properly.

Removing the plugin resolves the issue.

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
What other plugins do you have?
