### ISSUE TITLE
Version 4.0.3 is breaking  Obsidian

### ISSUE THREAD

**Issue by jmcd040** [mirnovov/obsidian-homepage#98]
### Details

Plugin V4.0.3; Obsidian v1.6.7, Windows 11. I've been using Obsidian for many months. Until about a week ago the Homepage plugin worked fine. I had it set to invoke my Dashboard workspace. In the last few days, using Homepage has left me with a blank screen, the one seen when you are in between workspaces. A few times it has just taken 10 seconds or so before the new workspace is loaded. But after one such failure to switch, I Obsidian becomes unresponsive. It becomes unresponsive even to clicking the X in the upper right corner. After uninstalling Homepage, I can switch using the Core plugin "Workspaces" with no problem. I've tried this on a small vault I keep for testing (i.e. has few files in it) with the same result.

### Debug information

I do have a lot of plugins installed.
![image](https://github.com/user-attachments/assets/d410b0d8-76e5-4ed2-bd3b-90600c3631b9)

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Should be fixed in 52fa3a6.
